#include "class_demo.h"
#include "class_song.h"

using namespace music;

//Forferdlig stor og kjip metode som i sisteliten ble laget for å ha
//en demo. 
song demo::grieg(){ 
	
	song mySong("Grieg", 200);
	
	mySong.addBar();
	note myNote("A#2", 8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("D#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F3",4);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("E3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("E3",4);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("D#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("B2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("D#3",4);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("A#2", 8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("D#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("G#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("G#3",2);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("A#2", 8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("D#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F3",4);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("E3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("E3",4);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("D#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("B2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("D#3",4);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("A#2", 8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("D#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("G#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("G#3",2);
	mySong.addNotes(myNote, mySong.barCount());
	
	//Goes down
	
	mySong.addBar();
	myNote = note("F3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("G3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C4",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C4",4);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("C#4",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#4",4);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C4",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C4",4);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("F3", 8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("G3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C4",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C4",4);
	mySong.addNotes(myNote, mySong.barCount());

	mySong.addBar();
	myNote = note("C#4",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#4",4);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C4",2);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("F3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("G3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C4",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C4",4);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("C#4",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#4",4);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C4",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C4",4);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("F3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("G3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C4",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C4",4);
	mySong.addNotes(myNote, mySong.barCount());

	mySong.addBar();
	myNote = note("C#4",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#4",4);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C4",2);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("A#1",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("D#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F2",4);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("E2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("E2",4);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("D#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("B1",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("D#2",4);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("A#1",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("D#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("G#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("G#2",2);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("A#1",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("D#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F2",4);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("E2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("E2",4);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("D#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("B1",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("D#2",4);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("A#1",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("D#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("G#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("G#2",2);
	mySong.addNotes(myNote, mySong.barCount());
	
	
	mySong.addBar();
	myNote = note("F3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("D#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("F3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("D#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("C3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("D#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C#3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	
	mySong.addBar();
	myNote = note("A2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("C3",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A#2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A2",8);
	mySong.addNotes(myNote, mySong.barCount());
	myNote = note("A#2",2);
	mySong.addNotes(myNote, mySong.barCount());
	
	return mySong;
}
